### ISSUE TITLE
[question] can it run on raspberry pi and coral usb accelerator? 

### ISSUE THREAD

**Issue by radu022003** [terry-voth/face-recongition-on-coral-dev-board#1]
Hello, 
I am curious if your example can work on a raspberry pi 4 and usb coral accelerator? 
Actually I only miss the part when the cropped face image is converted/inferred to embeddings.
Can you please advise?
Best regards

**Comment by terry-voth** [comment]
I personally haven't done anything with the Coral accelerator,  but here's a page that seems to illustrate exactly how to integrate Pi with Coral:
[Get started with Google Coral and Raspberry Pi](https://www.okdo.com/getting-started/get-started-with-google-coral-and-raspberry-pi/)

The image of the face to be recognized is converted to an embedding in the `get_name_for_face()` function on line 135 in face_recognizer.py.

Hope that helps.

**Comment by radu022003** [comment]
Thank you for your response, I do can work with raspberry pi and coral usb accelerator, that step is done. I can detect and extract faces from a given picture, the step I am missing is to get the embeddings for each face.
Thank you for narrowing down my search.
